### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by krishna-jha-25**
$ HOSTING_URL=your_host_uri yarn build -> $ HOSTING_URL=your_host_uri

### CODE REVIEW

**Comment by embbnux** [comment]
Hi @krishna-jha-25 We still need `yarn build` to build files after setting `HOSTING_URL`

**Comment by krishna-jha-25** [comment]
> Hi @krishna-jha-25 We still need `yarn build` to build files after setting `HOSTING_URL`
You are right but I think yarn build should be on another line as it may be confusing for some people. I accidentally added the yarn build along with the hosting url and it caused me a lot of trouble.

**Comment by embbnux** [comment]
> > Hi @krishna-jha-25 We still need `yarn build` to build files after setting `HOSTING_URL`
> > You are right but I think yarn build should be on another line as it may be confusing for some people. I accidentally added the yarn build along with the hosting url and it caused me a lot of trouble.

So I think you mean this:

```
$ HOSTING_URL=your_host_uri
$ yarn build
```

But when you set env independently, the env will keep in your current console session. I prefer "HOSTING_URL=your_host_uri yarn build", so the env will not influence other commands.

**Comment by krishna-jha-25** [comment]
> > > Hi @krishna-jha-25 We still need `yarn build` to build files after setting `HOSTING_URL`
> > > You are right but I think yarn build should be on another line as it may be confusing for some people. I accidentally added the yarn build along with the hosting url and it caused me a lot of trouble.
> 
> So I think you mean this:
> 
> ```
> $ HOSTING_URL=your_host_uri
> $ yarn build
> ```
> 
> But when you set env independently, the env will keep in your current console session. I prefer "HOSTING_URL=your_host_uri yarn build", so the env will not influence other commands.

Maybe I did something wrong but when I added the whole line as in the documentation it appended the `yarn build` in the hosting url and that caused me problems and then when I removed `yarn build` from the env and manually ran `yarn build` it worked perfectly fine.

**Comment by embbnux** [comment]
> > > > Hi @krishna-jha-25 We still need `yarn build` to build files after setting `HOSTING_URL`
> > > > You are right but I think yarn build should be on another line as it may be confusing for some people. I accidentally added the yarn build along with the hosting url and it caused me a lot of trouble.
> > 
> > 
> > So I think you mean this:
> > ```
> > $ HOSTING_URL=your_host_uri
> > $ yarn build
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > But when you set env independently, the env will keep in your current console session. I prefer "HOSTING_URL=your_host_uri yarn build", so the env will not influence other commands.
> 
> Maybe I did something wrong but when I added the whole line as in the documentation it appended the `yarn build` in the hosting url and that caused me problems and then when I removed `yarn build` from the env and manually ran `yarn build` it worked perfectly fine.

It is weird that it doesn't work with env. Do you use Window to run build? I tested at macOS and Ubuntu, it works well.

**Comment by krishna-jha-25** [comment]
> > > > > Hi @krishna-jha-25 We still need `yarn build` to build files after setting `HOSTING_URL`
> > > > > You are right but I think yarn build should be on another line as it may be confusing for some people. I accidentally added the yarn build along with the hosting url and it caused me a lot of trouble.
> > > 
> > > 
> > > So I think you mean this:
> > > ```
> > > $ HOSTING_URL=your_host_uri
> > > $ yarn build
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > But when you set env independently, the env will keep in your current console session. I prefer "HOSTING_URL=your_host_uri yarn build", so the env will not influence other commands.
> > 
> > 
> > Maybe I did something wrong but when I added the whole line as in the documentation it appended the `yarn build` in the hosting url and that caused me problems and then when I removed `yarn build` from the env and manually ran `yarn build` it worked perfectly fine.
> 
> It is weird that it doesn't work with env. Do you use Window to run build? I tested at macOS and Ubuntu, it works well.

Actually I was deploying on Netlify for testing so Netlify itself made the build.

**Comment by embbnux** [comment]
> > > > > > Hi @krishna-jha-25 We still need `yarn build` to build files after setting `HOSTING_URL`
> > > > > > You are right but I think yarn build should be on another line as it may be confusing for some people. I accidentally added the yarn build along with the hosting url and it caused me a lot of trouble.
> > > > 
> > > > 
> > > > So I think you mean this:
> > > > ```
> > > > $ HOSTING_URL=your_host_uri
> > > > $ yarn build
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > But when you set env independently, the env will keep in your current console session. I prefer "HOSTING_URL=your_host_uri yarn build", so the env will not influence other commands.
> > > 
> > > 
> > > Maybe I did something wrong but when I added the whole line as in the documentation it appended the `yarn build` in the hosting url and that caused me problems and then when I removed `yarn build` from the env and manually ran `yarn build` it worked perfectly fine.
> > 
> > 
> > It is weird that it doesn't work with env. Do you use Window to run build? I tested at macOS and Ubuntu, it works well.
> 
> Actually I was deploying on Netlify for testing so Netlify itself made the build.

Hi @krishna-jha-25 So I think it is issue at Netlify console, it doesn't support to run command with env as normal shell. You can submit issue to them.

**Review by parts-zap — APPROVED** [review]

**Comment by embbnux** [comment]
closing this.

**Pull request closed without merging**
